name: A workflow for my file
on:
  workflow_dispatch:
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: package
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0-alpha.0' 
      - uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'src/main.py'
          upload_exe_with_name: 'mcmod'
          options: -F -w, 
