name: A workflow for my file
on:
  workflow_dispatch:
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: package
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/main.py'
          upload_exe_with_name: 'mcmod'
          options: -F -w, 
